DONE_PROB = problem1

all: $(DONE_PROB)
problem1: problem1.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Not done
problem2: problem2.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Not done
problem3: problem3.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Not done
problem4: problem4.c
	$(CC) -Wall -I../include -o $@ $^
	sudo ./$@

clean:
	-rm $(DONE_PROB)