CFLAGS = -O0 -g -Wall -Werror

problem1: problem1.c
	$(CC) $(CFLAGS) -o $@ $^
	sudo ./$@

problem2: problem2.c
	$(CC) $(CFLAGS) -o $@ $^
	sudo ./$@

problem3: problem3.c
	$(CC) $(CFLAGS) -o $@ $^
	sudo ./$@

clean:
	-rm problem1 problem2 problem3