DONE_PROB = fibnacci problem1 problem2 problem3 problem4 problem5 problem7 problem9 problem10

all: $(DONE_PROB)
fibnacci: fibnacci.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem1: problem1.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem2: problem2.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem3: problem3.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem4: problem4.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem5: problem5.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Not done
problem6: problem6.c
	$(CC) -Wall -I../include -o $@ $^
	sudo ./$@

problem7: problem7.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Nor done
problem8: problem8.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem9: problem9.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

problem10: problem10.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

# Not done
problem11: problem11.c
	$(CC) -Wall -o $@ $^
	sudo ./$@

clean:
	-rm $(DONE_PROB)